# -*- coding: utf-8 -*-
"""Business Understanding, Deny Candra Kasuma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MP7Z62ZbAPCHJMFJrSPd0GEBMBIrs0y5

## **Business Understanding**

**Business Objective**

Tujuan utama proyek ini adalah untuk memahami faktor-faktor yang memengaruhi harga furnitur di platform e-commerce guna mendukung strategi harga yang lebih akurat dan kompetitif. Hal ini mencakup analisis berbagai atribut produk, ulasan pelanggan, dan tren pasar untuk membantu penjual dalam menentukan harga optimal serta meningkatkan daya saing di pasar. Selain itu, proyek ini juga bertujuan untuk meningkatkan pengalaman belanja pelanggan dengan memberikan rekomendasi harga yang lebih transparan dan berbasis data.

**Assess Situation**

Situasi bisnis yang mendasari analisis ini adalah persaingan yang ketat di industri furnitur online, di mana harga menjadi faktor utama dalam keputusan pembelian pelanggan. Tren harga yang fluktuatif dan adanya diskon dari berbagai penjual menuntut adanya strategi penentuan harga yang lebih dinamis dan berbasis data. Oleh karena itu, analisis harga furnitur menjadi krusial untuk membantu bisnis dalam mengoptimalkan strategi pemasaran dan meningkatkan profitabilitas.

**Data Mining Goals**

Mengidentifikasi faktor utama yang memengaruhi harga furnitur dengan menganalisis berbagai atribut produk, seperti jenis furnitur, ulasan pelanggan, dan metode pengiriman. Selain itu, proyek ini bertujuan untuk membangun model prediktif yang dapat memperkirakan harga berdasarkan data historis, sehingga dapat memberikan wawasan yang lebih mendalam dalam strategi penetapan harga.

**Project Plan**

**Data Understanding**: Eksplorasi dataset untuk memahami pola harga furnitur.

**Data Preparation**: Pembersihan data dan transformasi yang diperlukan.

**Modeling**: Prediksi harga menggunakan algoritma machine learning seperti regresi linear, random forest, atau XGBoost.

**Evaluation**: Mengukur akurasi model dengan MAE, RMSE, dan R².

**Deployment & Insight**: Menyediakan rekomendasi harga dan visualisasi data untuk pengambilan keputusan bisnis.
"""